env: local
http:
  #  host: 0.0.0.0
  host: 127.0.0.1
  port: 8000
security:
  admin_password: 123456
  # will be random
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    user:
      driver: sqlite
      dsn: storage/nunu-test.db?_busy_timeout=5000

pandora:
  domain:
    chat: https://chat.oaifree.com
    token: https://token.oaifree.com

log:
  log_level: info
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true